sudo: required
language: java
install: true
before_script: chmod a+x gradlew
script:
  - ./gradlew build
#  - ./gradlew jmh
  - ./gradlew -DEXECUTE_JMH=true jmh
  - ./gradlew -PmainClass=com.github.vitrifiedcode.javautilities.junit.JUnitRunner executeClassTest
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/