sudo: false
language: java
install: true
before_script: chmod a+x gradlew
script:
  - ./gradlew build
  - ./gradlew jmh
  - ./gradlew -PmainClass=com.github.vitrifiedcode.javautilities.junit.JUnitRunner executeClassTest
jdk: oraclejdk8